import { NONE, type ExtractedItem, type Section } from "./types";
export const demoTitle = "Northstar × Acme · Services agreement";
export const demoSections: Section[] = [
  {
    id: "C1",
    label: "§ 1 · Parties & effective date",
    document: "contract",
    text: "This Services Agreement is entered into between Northstar Studio Ltd (Customer) and Acme Cloud Services Ltd (Vendor), effective 1 January 2026.",
  },
  {
    id: "C2",
    label: "§ 2 · Term",
    document: "contract",
    text: "This Agreement expires on 31 December 2026.",
  },
  {
    id: "C3",
    label: "§ 3 · Renewal & notice",
    document: "contract",
    text: "The Agreement automatically renews for successive one-year terms unless either party provides written notice of non-renewal at least 60 calendar days before the expiry date.",
  },
  {
    id: "C4",
    label: "§ 4 · Service reporting",
    document: "contract",
    text: "The Vendor shall deliver a service performance report to the Customer on 15 October 2026.",
  },
  {
    id: "C5",
    label: "§ 5 · Security review",
    document: "contract",
    text: "The Vendor shall submit its annual security assessment by 15 November 2026.",
  },
  {
    id: "C6",
    label: "§ 6 · Termination",
    document: "contract",
    text: "Either party may terminate for material breach if the breach remains unremedied for 30 days after written notice. The day-count convention is not specified.",
  },
  {
    id: "C7",
    label: "§ 7 · Data return",
    document: "contract",
    text: "On termination, the Vendor shall return Customer data promptly in a mutually agreed format.",
  },
  {
    id: "P1",
    label: "Policy § 1 · Renewal review",
    document: "policy",
    text: "The Procurement team must complete an internal renewal review at least 90 calendar days before a supplier contract expires.",
  },
];
const citation = (id: string) => [
  { sectionId: id, quote: demoSections.find((s) => s.id === id)!.text },
];
const fixed = (date: string) => ({ ...NONE, type: "fixed" as const, date });
export const demoItems: ExtractedItem[] = [
  {
    key: "parties",
    kind: "party",
    title: "Customer & service provider",
    description:
      "Northstar Studio Ltd is the Customer. Acme Cloud Services Ltd is the Vendor.",
    party: "Both parties",
    certainty: "explicit",
    sources: citation("C1"),
    question: "",
    dateRule: NONE,
    reminderDays: 7,
  },
  {
    key: "effective",
    kind: "effective_date",
    title: "Agreement takes effect",
    description: "The agreement takes effect on 1 January 2026.",
    party: "Both parties",
    certainty: "explicit",
    sources: citation("C1"),
    question: "",
    dateRule: fixed("2026-01-01"),
    reminderDays: 7,
  },
  {
    key: "expiry",
    kind: "expiry",
    title: "Initial contract term ends",
    description: "The initial term expires on 31 December 2026.",
    party: "Both parties",
    certainty: "explicit",
    sources: citation("C2"),
    question: "",
    dateRule: fixed("2026-12-31"),
    reminderDays: 30,
  },
  {
    key: "renewal",
    kind: "renewal",
    title: "Automatic annual renewal",
    description:
      "Renews for successive one-year terms unless timely written non-renewal notice is given.",
    party: "Both parties",
    certainty: "explicit",
    sources: citation("C3"),
    question: "",
    dateRule: NONE,
    reminderDays: 7,
  },
  {
    key: "notice",
    kind: "notice",
    title: "Send notice of non-renewal",
    description:
      "Either party must provide written notice at least 60 calendar days before expiry to prevent automatic renewal.",
    party: "Either party",
    certainty: "explicit",
    sources: [...citation("C3"), ...citation("C2")],
    question: "",
    dateRule: {
      ...NONE,
      type: "relative",
      anchorId: "expiry",
      days: 60,
      direction: "before",
      basis: "calendar",
    },
    reminderDays: 7,
  },
  {
    key: "report",
    kind: "obligation",
    title: "Deliver service performance report",
    description: "Deliver the service performance report to the Customer.",
    party: "Acme Cloud Services Ltd",
    certainty: "explicit",
    sources: citation("C4"),
    question: "",
    dateRule: fixed("2026-10-15"),
    reminderDays: 7,
  },
  {
    key: "security",
    kind: "obligation",
    title: "Submit annual security assessment",
    description:
      "Submit the annual security assessment by the stated deadline.",
    party: "Acme Cloud Services Ltd",
    certainty: "explicit",
    sources: citation("C5"),
    question: "",
    dateRule: fixed("2026-11-15"),
    reminderDays: 14,
  },
  {
    key: "termination",
    kind: "termination",
    title: "Termination after unremedied breach",
    description:
      "Termination is permitted after an unremedied material breach and 30 days from written notice. No notice date or day-count convention is supplied.",
    party: "Either party",
    certainty: "uncertain",
    sources: citation("C6"),
    question:
      "When was written notice given, and are the 30 days calendar or business days?",
    dateRule: NONE,
    reminderDays: 7,
  },
  {
    key: "return",
    kind: "ambiguity",
    title: "“Promptly” has no defined deadline",
    description:
      "The Vendor must return data on termination, but the return deadline and format are not defined.",
    party: "Acme Cloud Services Ltd",
    certainty: "uncertain",
    sources: citation("C7"),
    question:
      "What exact deadline and data format should apply to data return after termination?",
    dateRule: NONE,
    reminderDays: 7,
  },
  {
    key: "policy",
    kind: "policy",
    title: "Complete internal renewal review",
    description:
      "Internal Procurement policy requires a review 90 calendar days before expiry. This is a policy obligation, not a contract amendment.",
    party: "Procurement team",
    certainty: "explicit",
    sources: [...citation("P1"), ...citation("C2")],
    question: "",
    dateRule: {
      ...NONE,
      type: "relative",
      anchorId: "expiry",
      days: 90,
      direction: "before",
      basis: "calendar",
    },
    reminderDays: 7,
  },
];
